# Generated by Django 4.1 on 2022-08-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_delete_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Brand name')),
                ('about', models.TextField(verbose_name='Brand about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Brand image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catbrand', to='main.category')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
